### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by oeey** [RealDeuce/xpcalc#1]
Curious if you could add a quick README to this project?  Something that describes what the calculation are (specifically the last number in (?)?

Example:
XP: 11800 (2) / 2 = 5900 (2950)

I get that the 11800 is the total XP, and the 5900 is the XP divided among the party, but what is the 2950?  Seems like it is half the divided XP, but why, and what is it useful for?

**Comment by RealDeuce** [comment]
I use half XP for when the encounter is not permanently resolved (ie: the party may have to come back to it).

**Comment by RealDeuce** [comment]
Done.
